send_photo:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: vk_notify
          domain: notify
    url:
      selector:
        text:
    file:
      selector:
        text:
    message:
      selector:
        text:
          multiline: true
