wall_post:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: vk_notify
          domain: notify
    message:
      selector:
        text:
          multiline: true
    file:
      selector:
        text:


send_file:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: vk_notify
          domain: notify
    file:
      required: true
      selector:
        text:
    message:
      selector:
        text:
          multiline: true

send_photo:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: vk_notify
          domain: notify
    url:
      selector:
        text:
    file:
      selector:
        text:
    message:
      selector:
        text:
          multiline: true
